"""Add preferences column to User model

Revision ID: 0925c32a6e51
Revises: 
Create Date: 2025-03-26 10:09:54.570774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0925c32a6e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('preferences')

    with op.batch_alter_table('sport_event', schema=None) as batch_op:
        batch_op.drop_column('sport_type')

    # ### end Alembic commands ###
